export const base_url = 'http://localhost:8080';
export const productOptionsWithImages = [
    { name: "Tomato", image: "/images/products/tomato.jpg" },
    { name: "Cucumber", image: "/images/products/cucumber.jpg" },
    { name: "Carrot", image: "/images/products/carrot.jpg" },
    { name: "Potato", image: "/images/products/potato.jpg" },
    { name: "Onion", image: "/images/products/onion.jpg" },
    { name: "Garlic", image: "/images/products/garlic.jpg" },
    { name: "Apple", image: "/images/products/apple.jpg" },
    { name: "Banana", image: "/images/products/banana.jpg" },
    { name: "Orange", image: "/images/products/orange.jpg" },
    { name: "Lemon", image: "/images/products/lemon.jpg" },
    { name: "Strawberry", image: "/images/products/strawberry.jpg" },
    { name: "Watermelon", image: "/images/products/watermelon.jpg" },
    { name: "Melon", image: "/images/products/melon.jpg" },
    { name: "Pepper", image: "/images/products/pepper.jpg" },
    { name: "Lettuce", image: "/images/products/lettuce.jpg" },
    { name: "Spinach", image: "/images/products/spinach.jpg" },
    { name: "Eggplant", image: "/images/products/eggplant.jpg" },
    { name: "Zucchini", image: "/images/products/zucchini.jpg" },
    { name: "Pumpkin", image: "/images/products/pumpkin.jpg" },
];